version: 2.1
defaults: &defaults
  machine:
    image: circleci/classic:edge

jobs:
  compile:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: ./scripts/ci-compile
          when: always
      - persist_to_workspace:
          root: '.'
          paths:
            - ./docker-image.img

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: '.'
      - run:
          command: ./scripts/ci
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: '.'
      - run: ./scripts/ci-prepare-release

workflows:
  version: 2
  default-workflow:
    jobs:
      - compile

      - test:
          requires:
            - compile

      - publish:
          requires:
            - test
          filters:
            branches:
              only: /^release-v.*/
